FROM node:10.15-alpine

ENV WORKDIR=/home/node/app

RUN mkdir -p /home/node/app

WORKDIR ${WORKDIR}

COPY package.json ${WORKDIR}

RUN npm install -g nodemon
RUN npm install && \
   npm run build

# COPY . ${WORKDIR}

COPY --chown=node:node . .

EXPOSE 3000

CMD [ "node", "server/index.js" ]
